version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    networks:
      - app-network

  frontend: 
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
